### ISSUE TITLE
Magazines occasionally disappear on re-joining world

### ISSUE THREAD

**Issue by Ryanicus2002** [Cubed-Development/Modern-Warfare-Cubed#236] opened 2023-08-03 11:03 UTC
## Describe the bug
Sometimes when disconnecting from a server (and potentially singleplayer too?) with a loaded weapon, the magazine will completely disappear from the gun upon rejoining the world. I don't know what the cause is, but I had an incident where my G3's magazine was deleted each time I rejoined, which I did 5 times in a row to confirm consistency.

I was unable to replicate the bug with any other weapons, and I was unable to replicate it in singleplayer. In fact after trying to replicate it with the other weapons, the bugged out G3 suddenly decided to start working normally. As a result I do not know what the cause was.

## To Reproduce
- [ ] I reproduced this issue with as few other mods as possible installed.
- [ X] I am unable to reproduce this issue consistently.

I can't offer any steps to reproduce since I haven't been able to find the cause myself. All I had done was join the multiplayer server and noticed my G3 was empty where it hadn't been before (and the magazine was deleted, not in inventory). The gun was crafted from the workbench in survival and had a couple attachments, in case that matters.

## Expected behavior
Expected that magazines would remain in the weapon on rejoin, rather than being fed to the magazine goblin.

## Versions
- Modern Warfare Cubed: [e.g. MWC-0.1-Dev-14] 
- Forge: [1.12.2 - 14.23.5.2859]

## Additional context

I'm sorry I can't provide more helpful information for reproducing this, but I figured I'd make yall aware of it at least. I'll keep an eye out for the same problem in the future in case I can figure out a cause.

**Comment by SticksDeveloper** [comment] 2023-08-03 17:39
Known issue under another name

**Comment by Desoroxxx** [comment] 2023-08-15 14:34
Duplicate of #248

**Closed by Desoroxxx** 2023-08-15 14:34 UTC
Labels: Bug
