### ISSUE TITLE
Spectator can shoot 

### ISSUE THREAD

**Issue by Charpyy** [Cubed-Development/Modern-Warfare-Cubed#336] opened 2023-12-26 13:11 UTC
### Describe the bug

When u are on gamemode spectator u are able to shoot weapon, i thought it was normal before i find out u cant do that with a vanilla bow

(This isn't a big bug, but I was watching a player when I accidentally killed the player by clicking on him.)

https://youtu.be/0iEl55IMXsQ

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Screenshots and/or videos

https://youtu.be/0iEl55IMXsQ

### Logs

no logs

### MWC Version

0.1 dev16

### Forge Version

1.12.2 - 14.23.5.2860

### Red Core Version

0.5 dev5

### MixinBooter Version

8.9

### Java Version

1.8 392

### Java Virtual Machine

Hotspot

### Operating System

Windows 11

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Koud-Wind** [comment] 2023-12-26 13:27
It has been fixed

**Comment by Desoroxxx** [comment] 2023-12-26 21:05
@Koud-Wind no, it is not public, this will be closed once the issue is actually fixed in prod

**Closed** 2024-03-13 16:49 UTC
Labels: Bug
