### ISSUE TITLE
Shield Bug

### ISSUE THREAD

**Issue by NickCodesStuf** [Cubed-Development/Modern-Warfare-Cubed#215] opened 2023-07-17 22:45 UTC
## Description
After a certain series of events a shield in the offhand will enter into a bugged state. In this bugged state shields have the following behavior.
1. In first person the shield appears to stay up after right click has been released
2. Attacks are blocked as if the shield was active
3. The player is unable to break blocks or hit entites until the player disengages the state (i.e. right click no longer works for all except 4)
4.  The player is able to use guns from MWC (this includes reloading, firing, and even modifying any gun in the main hand even if it was not used to reproduce this glitch)
5. The shield will appear inactive to 3rd person and other players unless a VMC gun is adsing or firing (but 2 still holds true when attacked)
6. The player leaves this state by either right-clicking again with anything that isnt a VMC gun, opening an inventory, or pausing the game with the esc key.

## Reproducibility
[X] I reproduced this issue with as few other mods as possible installed.
[] I am unable to reproduce this issue consistently.

## To Reproduce
1. Equip a shield in the offhand, a VMC gun in the hotbar, and an empty slot (or any item that will not interact when right clicked) in the main hand.
2. hotkey or scroll to the vmc gun
3. release right click

## Expected behavior
The shield should be disengaged as soon as right click is released where consecutive right clicks should toggle only the gun.

## Versions
Modern Warfare Cubed: mwc-0.1-Dev-14
Forge: 1.12.2 - 14.23.5.2860
Java: JDK 8 - 352b08
Specification:
OS: Windows 10
CPU: Ryzen 7 5900X
GPU: RTX 3080
RAM Allocated: 8GB

## Additional context
This was an issue that was in the original VMW

**Comment by NickCodesStuf** [comment] 2023-07-17 22:47
Sorry for the sloppy syntax I am dumb

**Comment by Desoroxxx** [comment] 2023-12-18 22:59
Duplicate of #248

**Closed by Desoroxxx** 2023-12-18 22:59 UTC
Labels: Bug, Need Investigation
