### ISSUE TITLE
Workbench does not keep track of the total ammount of items in it's inventory

### ISSUE THREAD

**Issue by Milosauce** [Cubed-Development/Modern-Warfare-Cubed#69] opened 2023-04-30 07:10 UTC
## Describe the bug

If you put 2 stacks of the same item into the gun bench, it will only check the first stack to determine if you have enough to craft something.

> Remember that a great explanation leads to a greater understanding

## Reproducibility
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox, replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.

- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

***Steps to reproduce the behavior:***

1. Go to the gun bench
2. in the top left, put a stack of plastic plates. Just to the left of that, put another 5 plastic plates.
3. Go to armor and try to craft any sort of armor that requires only plastic plates (such as combat boots)
4. See that even though there is a total of 69 plastic plates in the bench, it will not let you craft armor that requires less than that.

## Expected behavior

I expect the gun bench to not let you craft the item because it only looks at the first stack instead of all stacks of an item.

## Screenshots or/and videos

![image](https://user-images.githubusercontent.com/105452264/235340191-19dcb6e5-acf3-43e0-959e-2df0b5014d22.png)
![image](https://user-images.githubusercontent.com/105452264/235340199-f2ccc0d1-0137-44d6-9f71-baf5511858af.png)

## Versions

- Modern Warfare Cubed: Modern-Warfare-Cubed-0.1-Dev-9
- Forge: 1.12.2-14.23.5.2859
- Java: JDK 8 - 371-b11
- Java JVM: I dont have Java JVM

## Specification:

- OS: Windows 10
- CPU: AMD FX-6100 Six-Core Processor
- GPU: Radeon RX 6700 XT
- RAM Allocated: 6GB

**Comment by SticksDeveloper** [comment] 2023-05-01 02:51
hmmm

**Comment by MrRedstoneA1** [comment] 2023-05-12 13:52
I also encountered this issue. The mod checks the stacks from left to right but stops at the first stack even if there are other stacks.

**Comment by Desoroxxx** [comment] 2023-05-12 14:25
Technically a duplicate of #35

**Closed by Desoroxxx** 2023-05-12 14:25 UTC
Labels: Bug

**Comment by strubium** [comment] 2023-05-12 14:39
> Technically a duplicate of #35

I like that you edited the title, then said it was a duplicate

**Comment by Desoroxxx** [comment] 2023-05-12 14:40
> I like that you edited the title, then said it was a duplicate

Okay?

**Comment by strubium** [comment] 2023-05-12 14:43
I mean it is a duplicate
