### ISSUE TITLE
Incompatibility With Mo'Bends

### ISSUE THREAD

**Issue by zandwage** [Cubed-Development/Modern-Warfare-Cubed#481] opened 2024-09-03 22:32 UTC
### Describe the bug

Holding weapons simply doesn't render the arms. I believe it is an issue if the Mo'Bends animations are loaded, because if you first go into a world, and don't go into 3rd person, if you hold one of the weapons, the arms still render. I would really love to see compatibility with Mo'Bends, as it is an incredible mod.

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Screenshots and/or videos

https://github.com/user-attachments/assets/492a17fb-5dda-498f-b173-191785037ff5

### Logs

https://mclo.gs/mi4O5ql

### MWC Version

0.1.8

### Forge Version

1.12.2 - 14.23.5.2860

### Red Core Version

0.6 Dev 7

### MixinBooter Version

8.0

### Java Version

Java 8

### Java Virtual Machine

Hotspot

### Operating System

Windows 10

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Desoroxxx** [comment] 2024-09-03 23:44
Duplicate of #136

**Closed by Desoroxxx** 2024-09-03 23:44 UTC
Labels: Bug
