### ISSUE TITLE
crash when trying to make night vision goggles in workbench

### ISSUE THREAD

**Issue by ArandomHitman** [Cubed-Development/Modern-Warfare-Cubed#463] opened 2024-07-11 20:15 UTC
### Describe the bug

Basically I was trying to get a new pair of night vision goggles since my old ones got lost when I died from bandits. So I went to the workbench to craft one, clicked on the gear/armor tab, clicked the goggles, and then I got a "shutting down internal server" screen for 3 seconds, and then this crash.

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

Not really applicable, but here ig:https://mclo.gs/8S8rFC3

### Crash Reports

https://mclo.gs/DGCqb6h

### MWC Version

0.1.7

### Forge Version

1.12.2 latest

### Red Core Version

1.7-1.12-0.5.1

### MixinBooter Version

9.1

### Java Version

1.8 -392

### Java Virtual Machine

Hotspot

### Operating System

Windows 11

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Desoroxxx** [comment] 2024-08-15 15:06
Duplicate of #419

**Closed by Desoroxxx** 2024-08-15 15:06 UTC
Labels: Bug
