### ISSUE TITLE
Unable to load recipe online

### ISSUE THREAD

**Issue by Koud-Wind** [Cubed-Development/Modern-Warfare-Cubed#60] opened 2023-04-18 06:28 UTC
## Describe the bug

***Unable to load the recipe on the host side when online, This may be a serious bug***

## To Reproduce

***Steps to reproduce the behavior:***
1. Start with 2 minecraft
2. The host enters the map and is open to the local area network
3. At this point, the recipe can be displayed on the host side, Allow another client to enter the local area network (do not enter single player games)
4. Another client cannot display the recipe
additional
5. Keep LAN enabled, Client exits LAN, modify the JSON file of the recipe, and enter a single player game
6. At this point, the recipe has been modified and can be displayed (the LAN of the other minecraft remains enabled)
7. Exit the single player game and enter the local area network. The recipe has been modified (it appears to be fake)
8. Fortunately, the client cannot create anything from the fake recipe displayed to him
9. If the host creates items other than fake recipes (i.e. actual recipes), the client will directly crash
[crash-2023-04-18_14.01.09-client.txt](https://github.com/Cubed-Development/Modern-Warfare-Cubed/files/11258601/crash-2023-04-18_14.01.09-client.txt)

## conclusion
I think the client cannot correctly read the recipe cache from the host (perhaps not including the server), and the recipe is not actively loaded from the moment the game starts

**Comment by Koud-Wind** [comment] 2023-04-18 06:31
I just noticed that this may be a problem that has already been reported

**Comment by SticksDeveloper** [comment] 2023-04-18 06:42
Already a known Issue,

LAN has been broken and Is an issue that will be fixed later
Regular Multiplayer works.

**Closed by SticksDeveloper** 2023-04-18 06:42 UTC
Labels: Bug

**Comment by Desoroxxx** [comment] 2023-04-18 09:11
Duplicate of #36
