### ISSUE TITLE
[Post Process] On-Screen Rain and Snow crashes game

### ISSUE THREAD

**Issue by IgiariValkyr** [Cubed-Development/Modern-Warfare-Cubed#4] opened 2023-02-27 07:57 UTC
## Describe the bug

During weather cycles, the on-screen rain and snow VFX crash the game to launcher.

## Reproducibility

- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

1. Config file > onScreenRainAndSnow=true
2. Start world
3. Set weather to rain

## Logs or/and crash reports

Crash log with just MWC alone
https://mclo.gs/y31O1Qu

Latest crash log before specific cause was found in config.
https://mclo.gs/8bVJisa

## Versions

- Modern Warfare Cubed: MWC-0.1-Dev-2
- Forge: 1.12.2 - 14.23.5.2859
- Java: JDK8
- Java JVM: 🤷 

## Specification:

- OS: Windows 10
- CPU: Ryzen 7 3700X
- GPU: Radeon RX 6700 XT
- RAM Allocated: 8GB

***All of these info below are not necessary but may become necessary depending on the issue***

- CPU Speed: 3.58GHz base / 4.18GHz current
- CPU Core: 8
- CPU Threads: 16
- RAM Size: 32GB
- RAM Speed: 🤷 
- Storage Type: SSD
- GPU VRAM: 12GB

> Most of these information can be found in the task manager

## Additional context

***Add any other context about the problem here.***

**Comment by Paneedah** [comment] 2023-02-27 17:58
This is not a bug report for `Modern Warfare Cubed`, it's a report for `Paneedah's Modern Warfare` which is no longer supported.

Please do not submit reports for issues relating to that GitHub repository here.

**Comment by JustDesoroxxx** [comment] 2023-03-10 15:50
> This is not a bug report for `Modern Warfare Cubed`, it's a report for `Paneedah's Modern Warfare` which is no longer supported.
> 
> Please do not submit reports for issues relating to that GitHub repository here.

Sike

**Comment by Paneedah** [comment] 2023-03-10 16:41
Hi, seems like you're running Java Version 1.8.0_51.

Could you use https://adoptium.net/en-gb/temurin/releases/?version=8 and update to the latest version (you are about 300 versions out of date).

I've tested and this isn't directly your issue, but doing this would be very recommended.

**Comment by JustDesoroxxx** [comment] 2023-03-10 17:08
It appear you might be using the Curse Forge launcher if so follow these instruction to change the Java that Curse Forge launcher uses once newer Java installed https://youtu.be/EGUsEq6HOd0?t=25

**Comment by Koud-Wind** [comment] 2023-03-11 02:37
Have you closed the bobView?

**Comment by Koud-Wind** [comment] 2023-03-11 02:37
I guess you closed it

**Comment by Paneedah** [comment] 2023-03-11 11:22
> Have you closed the bobView?

This isn't an issue with the view bobbing, I've tested that a little bit.

After talking to Jim, I've been made aware that he has disabled the fog feature as per Vic's request. My current thought is that while disabling the fog and removing it, he cut off some code which is required for the custom rain to work.

**Comment by SticksDeveloper** [comment] 2023-04-28 14:13
> > Hi, seems like you're running Java Version 1.8.0_51.
> > Could you use https://adoptium.net/en-gb/temurin/releases/?version=8 and update to the latest version (you are about 300 versions out of date).
> 
> Ayo, Java 8 is divided into multiple build numbers, so the person is probably using the correct version.
> 
> Here's a quote from [Oracle](https://www.oracle.com/java/technologies/javase/8u51-relnotes.html): SE Development Kit 8, Update 51 (JDK 8u51). The full version string for this update release is 1.8.0_51-b16

Java 8 Is on u300 something

**Comment by strubium** [comment] 2023-04-28 14:20
> JDK 8 Is on u300 something

8u371

**Comment by Paneedah** [comment] 2023-05-11 22:52
@Desoroxxx Did you manage to test this? I believe you mentioned you may have possibly found a solution?

**Closed** 2023-12-21 19:07 UTC
Labels: Bug, Need Investigation
