### ISSUE TITLE
Broken gun state

### ISSUE THREAD

**Issue by Officialaumember** [Cubed-Development/Modern-Warfare-Cubed#316] opened 2023-12-18 02:55 UTC
## Describe the bug

Stops me from using my gun

***A clear and concise description of what the bug is.***

Gun becomes unusable to any degree other than holding. Only happens on weapon system version 2 guns (in the tests I conducted). Ammo counter will bug showing '-' in both the magazine's maximum capacity and current amount filled. I can't aim the gun, reload it, unload it, shoot it, or even switch from semi to auto etc. I am still able to move between inventory slots.

## Reproducibility
reload a weapon system version 2 gun while crouching.

## To Reproduce

1. Obtain a gun that uses Weapon System Version 2.
2. Reload the gun.
3. Once the gun is reloaded, reload it again. This time as the gun reloading animation plays, hold down (or toggle) crouch.
4. wait until the animation is done.
5. You just broke your gun

## Expected behavior

I expected a working and reloaded gun.

https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/154106077/39ed448f-7c38-477b-8d0e-5a23a2a7dbd3

## Versions

- Modern Warfare Cubed: Modern-Warfare-Cubed-0.1-Dev-14
- Forge: 1.12.2 - 14.23.5.2860
- Java: 21 2023-09-19 LTS
- Java JVM: idk

## Specification:

- OS: Windows 10
- CPU: Ryzen 5 3600X
- GPU: Radeon RX 6750 XT
- RAM Allocated: 5120 MB

***All of these info below are not necessary but may become necessary depending on the issue***

- CPU Speed: Base clock: 3.80   Boost clock: 4.40Ghz
- CPU Core: 6 cores
- CPU Threads: 12 threads
- RAM Size: 16gb
- RAM Speed: 3200mhz
- Storage Type: SSD
- GPU VRAM: 12GB

Thing to note:
I initially found this with an additional 50+ mods installed, but the glitch was still present in an environment with only RedCore and Modern Warfare Cubed installed.

**Comment by Desoroxxx** [comment] 2023-12-18 10:04
Duplicate of #248

**Closed by Desoroxxx** 2023-12-18 10:04 UTC
Labels: Bug
