### ISSUE TITLE
Attachement Dupe

### ISSUE THREAD

**Issue by boubouleuh** [Cubed-Development/Modern-Warfare-Cubed#157] opened 2023-06-05 12:07 UTC
## Describe the bug

When you have a "bugged weapon," you can infinitely remove any attachments which include magazine.

There is also an ammo bug that eat ammo. It is similar to this bug, but when the weapon is not loaded, you cannot reload it properly when this bug occurs.

It seems like the weapon is stuck in a single state.

## Reproducibility
- [ ] I reproduced this issue with as few other mods as possible installed.
- [X] I am unable to reproduce this issue consistently.

## To Reproduce

***Steps to reproduce the behavior:***

1. Have a bugued weapon is "bugged" (cant get a bugged weapon everytime you want, just need to wait, that can happen when you pickup a weapon or same if you already have it on you)
2. Unload ammo or attachment
3. Pick up the weapon in the inventory slot
4. Put the weapon in an inventory slot (the same or an other)
5. Repeat the process infinitely

## Expected behavior

Cant have a bugged weapon, can everytime reload and unload properly, no extra ammo / attachment when you pick up from the inventory and put it in. 

## Screenshots or/and videos

[video](https://clipchamp.com/watch/h8HLimjVwVg)

- Modern Warfare Cubed: 0.1-Dev-12
- Forge: 1.12.2 - 14.23.5.2860
- Java: JDK 8 (default curseforge one)

## Specification:

- OS: WIndows 11
- CPU: Ryzen 5 2600X
- GPU: Nvidia GTX 1060
- RAM Allocated: 10gb

***All of these info below are not necessary but may become necessary depending on the issue***

- CPU Speed: 3.60ghz boost around 4ghz
- CPU Core: 6
- CPU Threads: 12
- RAM Size: 32GB
- RAM Speed: 3200 MHz
- Storage Type: SSD
- GPU VRAM: 6GB

**Comment by Desoroxxx** [comment] 2023-07-13 01:06
![](https://github.trello.services/images/mini-trello-icon.png) [0.1 Bug Bash](https://trello.com/c/3LscCjLD/33-01-bug-bash)

**Comment by Desoroxxx** [comment] 2023-08-15 14:35
Duplicate of #248

**Closed as not planned by Desoroxxx** 2023-08-15 14:35 UTC
Labels: Bug, Need Investigation
