### ISSUE TITLE
Gun models bugged

### ISSUE THREAD

**Issue by Tapifiy** [Cubed-Development/Modern-Warfare-Cubed#37] opened 2023-03-25 16:43 UTC
![2023-03-25_17 37 28](https://user-images.githubusercontent.com/126156001/227730411-905aff44-c4be-49c3-b78d-96921187f0d7.png)
![2023-03-25_17 39 55](https://user-images.githubusercontent.com/126156001/227730412-52805596-47f2-4095-a98d-d8cfd0b9404e.png)
![2023-03-25_17 39 56](https://user-images.githubusercontent.com/126156001/227730413-dd456890-398c-47d2-8ea5-a0a27dc42c13.png)
![2023-03-25_17 39 57](https://user-images.githubusercontent.com/126156001/227730414-6012f2cf-141e-4a22-b647-cf4172dc87f8.png)
![2023-03-25_17 39 59](https://user-images.githubusercontent.com/126156001/227730415-a70a0c6e-9131-4506-b413-4f49af80d6f6.png)
![2023-03-25_17 40 02](https://user-images.githubusercontent.com/126156001/227730416-037c8fb6-1ce9-49cd-b0fd-d91657007978.png)
![2023-03-25_17 40 03](https://user-images.githubusercontent.com/126156001/227730417-4896edc0-1aea-44a9-a708-cc1a2c9a7de8.png)
![2023-03-25_17 40 05](https://user-images.githubusercontent.com/126156001/227730419-86dd7d2f-e9c7-4420-948d-4e6be2c9fd97.png)

**Comment by SticksDeveloper** [comment] 2023-03-25 17:11
Colt 1911 is not a bug thats our test gun for obj models it was released publicly by accodent

**Comment by Koud-Wind** [comment] 2023-03-26 06:55
I have feedback on this issue: https://github.com/Cubed-Development/Modern-Warfare-Cubed/issues/18

**Comment by Paneedah** [comment] 2023-05-14 12:16
Colt1911 has been fixed in Dev-11. It was being temporarily used as Stick's test gun.

**Comment by Braiam23** [comment] 2023-09-21 00:08
Let me close this issues repository, most of the problems you mention have already been fixed.

**Closed by Braiam23** 2023-09-21 00:08 UTC
Labels: Bug
