### ISSUE TITLE
Gun attachments bug/Gun loses attachments when dropped

### ISSUE THREAD

**Issue by minebloxian334** [Cubed-Development/Modern-Warfare-Cubed#289] opened 2023-10-18 12:01 UTC
I'm not sure if someone had this bug but there was an issue where the gun's attachments (I used the M82 Barrett) just got deleted and even the ammo inside just disappeared. I had to use multiple attachments to get it fixed but also when I dropped my weapon, everything just resets, ammo, attachments... GONE! I'm not sure how this happens but I was just having this issue when I was only in survival

Edit: Also there is a bug where gun also loses its attachments and ammo inside it when placing gun in a different inventory slot

**Comment by Desoroxxx** [comment] 2023-11-16 22:14
Duplicate of #248

**Closed by Desoroxxx** 2023-11-16 22:14 UTC
Labels: Bug
