### ISSUE TITLE
Ammo materials dupe

### ISSUE THREAD

**Issue by AstralOreo** [Cubed-Development/Modern-Warfare-Cubed#444] opened 2024-06-02 16:07 UTC
### Describe the bug

If i put 60 of gunpowder and 60 of copper into an ammo socket and then craft 10 of a random ammo (5.56x45mm, .50BMG, etc) I will get 60 of that ammo. Now, if i then dismantle it i won't have 60 of copper and gunpowder, but rather 5 stacks and 40 of each of the 2 materials. I tried using a modpack with various mods and then MWC only, and the result is the same. 
(Sorry for bad english if it's hard to understand the bug, i put a link for 2 videos where i do the dupe).

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Screenshots and/or videos

https://drive.google.com/drive/folders/1C5zdbQ5dWiOHwPFJ-TVX5jwWcVWMUPpZ?usp=sharing

### Logs

https://mclo.gs/AsYvvoo

### MWC Version

0.1.6

### Forge Version

1.12.2 14.23.5.2859

### Red Core Version

0.6 Dev4

### MixinBooter Version

8.8

### Java Version

1.8.0_51

### Java Virtual Machine

Hotspot

### Operating System

Windows 11

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Desoroxxx** [comment] 2024-11-25 17:05
Duplicate of #420

**Closed by Desoroxxx** 2024-11-25 17:05 UTC
Labels: Bug
