### ISSUE TITLE
When the player's head approaches some MWC blocks, they will suffer suffocation damage

### ISSUE THREAD

**Issue by Koud-Wind** [Cubed-Development/Modern-Warfare-Cubed#94] opened 2023-05-12 17:46 UTC
## Describe the bug

For example: mw:ammo_press, mwc:ump45_gfl, mwc:scarecrow

## To Reproduce

1. 
![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/123817318/ea483da3-9e4b-4012-923c-408b75624399)
2. Get close to it

**Comment by SticksDeveloper** [comment] 2023-05-12 17:59
It's not a bug It's a feature >:)

**Comment by SticksDeveloper** [comment] 2023-05-12 17:59
this is because the hitbox is setup in a special way will get fixed soon

**Comment by Desoroxxx** [comment] 2023-05-12 20:42
> this is because the hitbox is setup in a special way will get fixed soon

Na this is because how fluffed up current TE are will be fixed TM

**Closed** 2023-07-16 18:41 UTC
Labels: Bug
