### ISSUE TITLE
ADS will hold under specific conditions

### ISSUE THREAD

**Issue by NickCodesStuf** [Cubed-Development/Modern-Warfare-Cubed#214] opened 2023-07-17 22:17 UTC
## Description
When ADS is held down and a gun is unable to fire, say whenever a gun is out of ammo or a lever action needs to cycle, after left clicking, the ads button can be released and the gun will stay ADSed. 

## Reproducibility
- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce
Method 1 - unloaded a gun
1. Get any gun with no ammo (m4, ak74, mares leg, etc)
2. Hold Right Click to ADS
3. While ADSed Left Click to "fire", this will not work for obvious reasons
4. Release Right Click and observe that ADS is still enabled

## Expected behavior
ADS should be released as soon as the key is released no matter what the previous keystrokes are

## Versions

- Modern Warfare Cubed: mwc-0.1-Dev-14
- Forge: 1.12.2 - 14.23.5.2860
- Java: JDK 8 - 352b08

## Specification:

- OS: Windows 10
- CPU: Ryzen 7 5900X
- GPU: RTX 3080
- RAM Allocated: 8GB

## Additional context
To my knowledge this issue was not granfathered in from VMW

**Comment by Paneedah** [comment] 2023-07-17 22:18
Duplicate of #112

**Closed by Paneedah** 2023-07-17 22:18 UTC
Labels: Bug, Duplicate
