### ISSUE TITLE
I cant reload and shoot my gun

### ISSUE THREAD

**Issue by yongyong1015** [Cubed-Development/Modern-Warfare-Cubed#305] opened 2023-11-20 06:37 UTC
When I load the gun, it only shows motion and it doesn't load. If I load it twice, the gun loaded, but it fire only one shot regardless of the magazine. Even it is weapon system 2! For example, I try load my colt python once, it didn't loaded. It still remain 0|6. And I reload once more, gun loaded looks success but If i fire my gun, It just fired once and left ammo just gone.
Im using Custom NPC mod and worldedit.
![Minecraft 1 12 2 2023-11-20 15-03-22](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/147421127/b14f09ed-f351-4424-a56a-d813ef6d498a)
![Minecraft 1 12 2 2023-11-20 15-01-25](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/147421127/16687bd4-be99-4615-8a53-f92209b74131)

[ ] I reproduced this issue with as few other mods as possible installed.
[ V] I am unable to reproduce this issue consistently.

Hold Any gun.
Click R
Click R again
Left click to fire gun

Versions
Modern Warfare Cubed: [MWC-01-DEV14]
Forge: [1.12.2 - 14.23.5.2859]
Java: [Java version 8, Update 391, build 1.8.0_391-b13)
Java JVM: [idk]

**Comment by Desoroxxx** [comment] 2023-11-20 13:05
Restart your game.

Duplicate of #248

**Closed by Desoroxxx** 2023-11-20 13:05 UTC
Labels: Bug
