### ISSUE TITLE
Bloom and postflat errors, minecraft world wont start, cause crash

### ISSUE THREAD

**Issue by Walker-TJA** [Cubed-Development/Modern-Warfare-Cubed#435] opened 2024-05-14 19:15 UTC
### Describe the bug

Please help i cant play your mod because of runtime exceptions when i run my game through prism launcher, please read crash log!

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

https://mclo.gs/RRAjdr6

### Debug Logs

https://mclo.gs/RRAjdr6

### Crash Reports

https://mclo.gs/RRAjdr6

### MWC Version

0.1.5

### Forge Version

1.12.2 - 14.23.5.2859

### Red Core Version

0.5.1

### MixinBooter Version

9.1

### Java Version

1.8 - 8

### Java Virtual Machine

Hotspot

### Operating System

Kali Linux, latest, i think

### GPU Vendor

Intel

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Plite7067** [comment] 2024-05-15 10:57
Duplicate of this issue: https://github.com/Cubed-Development/Modern-Warfare-Cubed/issues/147.\
The fix is listed at the bottom, but involves building the mod locally until a new version of mwc comes out.\
I have a fixed jar, but not sure if i'm allowed to share it.

**Closed** 2024-05-15 15:45 UTC
Labels: Bug
