### ISSUE TITLE
Scope shaders conflict with GregTech CEU

### ISSUE THREAD

**Issue by DrNuget** [Cubed-Development/Modern-Warfare-Cubed#302] opened 2023-11-14 22:28 UTC
## Describe the bug

Modern Warfare mod scope shaders make the screen blank if you also have Gregtech CEU installed.

## Reproducibility

- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

1. Make a modpack with MWC, GTCEU and their required dependencies installed
2. Change the following settings in the mwc.cfg file so the game doesn't crash:
    B:enableFlashShaders=false
    B:enableGunShaders=false
    B:enableScreenShaders=false
    B:enableWorldShaders=false
3. Open a new world and equip a gun with a scope attachment on it

## Screenshots or/and videos

![image](https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/34383935/3ec8768b-5bbb-4dc5-9f4b-6d17cf7f4ef7)

## Versions

- Modern Warfare Cubed: MWC-0.1-Dev-14
- Forge: 1.12.2 - 14.23.5.2860
- Java: JDK 8 - 392-b08

## Specification:

- OS: Manjaro Linux
- CPU: Ryzen 5 5600X
- GPU: Radeon RX 5700 XT
- RAM Allocated: 16GB

**Comment by Desoroxxx** [comment] 2023-11-16 22:13
Spirit duplicate of #212

**Closed by Desoroxxx** 2023-11-16 22:13 UTC
Labels: Bug
