### ISSUE TITLE
Crash when I select firemode

### ISSUE THREAD

**Issue by javiburatos** [Cubed-Development/Modern-Warfare-Cubed#460] opened 2024-07-08 19:19 UTC
### Describe the bug

When I change the firemode my game Crash

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

https://mclo.gs/dIItWCo

### Crash Reports

https://mclo.gs/CunPxW6

### MWC Version

0.1.7

### Forge Version

14.23.5.2860

### Red Core Version

0.5.1

### MixinBooter Version

9.1

### Java Version

1.8 - 411

### Java Virtual Machine

Hotspot

### Operating System

Windows 10

### GPU Vendor

AMD

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by javiburatos** [comment] 2024-07-09 23:28
Ok, the error happens when reload too

**Comment by Desoroxxx** [comment] 2024-08-15 15:05
Duplicate of #459

**Closed by Desoroxxx** 2024-08-15 15:05 UTC
Labels: Bug
