### ISSUE TITLE
Dupe Magazine

### ISSUE THREAD

**Issue by Creat789** [Cubed-Development/Modern-Warfare-Cubed#244] opened 2023-08-13 16:51 UTC
Describe the bug
When a player unloads the magazine from a weapon, the magazine remains in the weapon and also a copy of the magazine is added to the player's inventory, resulting in duplication.

This duplication bug compromises the balance and fairness of gameplay.

Reproducibility
 I reproduced this issue with as few other mods as possible installed.
 I am unable to reproduce this issue consistently.
To Reproduce

Equip a weapon with a magazine.
Unload the magazine from the weapon.
Observe that the magazine is still present in the weapon.
Also observe that a duplicate magazine with 0 ammunition is added to the player's inventory.
Expected behavior
When unloading the magazine from the weapon, the magazine should be removed from the weapon and transferred to the player's inventory without any duplication.

Screenshots or/and videos
No video,
Logs or/and crash reports (SPAM WHY ?)
https://pastebin.com/nC3VbWMy

Versions
Modern Warfare Cubed: [e.g. MWC-0.1-Dev-14]
Forge: 14.23.5.2847
Java: JDK 8
Java JVM: [e.g. Hotspot]
Specification:
OS: Windows 11
RAM Allocated: 16GB

**Comment by Paneedah** [comment] 2023-08-13 17:06
Hey there.

First of all, please use version 0.1-Dev-14. Dev-15 is still in production and is not released for a reason.

Secondly, please attach a video showing the issue, as I am unable to reproduce it with any gun that I have tried (ensure that you're only using weapons under version 2 not 1).

Let us know once you've done these two, and reupload your logs.

**Comment by Desoroxxx** [comment] 2023-08-15 13:28
Duplicate of #248

**Closed by Desoroxxx** 2023-08-15 13:28 UTC
Labels: Bug
