### ISSUE TITLE
The gun is unusable.

### ISSUE THREAD

**Issue by fzrdwa123456** [Cubed-Development/Modern-Warfare-Cubed#368] opened 2024-03-14 04:26 UTC
### Describe the bug

After replacing the magazine, the gun is unusable.

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

没有日志

### MWC Version

0.1.1

### Forge Version

1.12.2 forge 14.23.5.2860

### Red Core Version

0.6 dev 3

### MixinBooter Version

9.1

### Java Version

1.8

### Java Virtual Machine

Hotspot

### Operating System

windows 11

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fzrdwa123456** [comment] 2024-03-14 04:27
https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/130232431/386ebc6a-d04a-4f22-bc71-01c404534a92

**Comment by fzrdwa123456** [comment] 2024-03-14 04:34
https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/130232431/c474d9f6-c58d-469e-b7f3-8e3853ba2e78

**Comment by fzrdwa123456** [comment] 2024-03-14 04:37
In the case of crouching and changing bullets in creative mode, I don't know if there will be such a problem in survival mode

**Comment by fzrdwa123456** [comment] 2024-03-14 04:39
The gun can't be thrown away yet

**Comment by Desoroxxx** [comment] 2024-03-14 07:13
Duplicate of #248

**Closed** 2024-03-14 07:14 UTC
Labels: Bug
