### ISSUE TITLE
Weird scope bug

### ISSUE THREAD

**Issue by chair-man-f** [Cubed-Development/Modern-Warfare-Cubed#386] opened 2024-03-19 01:42 UTC
### Describe the bug

scopes don't zoom in on terrain but does zoom in on entities

https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/117324349/4d0a602f-9c08-416c-8606-476c055acb03

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

https://mclo.gs/rIcRt0G

### MWC Version

0.1.3

### Forge Version

1.12.2 14.23.5.2860

### Red Core Version

0.6 dev 3

### MixinBooter Version

9.1

### Java Version

1.8 402

### Java Virtual Machine

Hotspot

### Operating System

MacOS (Apple M1 pro gpu)

### GPU Vendor

AMD

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Desoroxxx** [comment] 2024-08-16 14:55
Duplicate of #212

**Closed by Desoroxxx** 2024-08-16 14:55 UTC
Labels: Bug
