### ISSUE TITLE
Magma server freezes when encountering explosions 

### ISSUE THREAD

**Issue by BoomerSchmirtz** [Cubed-Development/Modern-Warfare-Cubed#89] opened 2023-05-12 07:35 UTC
## Describe the bug

When an explosion occurs and it hits a player or an entity the Magma server freezes without any errors in the console.

After many tests I got the bug to replicate when logged on to a Magma server with another player and hitting them with a MWC explosion - such as grenade, RPG, etc...

## Reproducibility
- [x] I am able to reproduce this issue consistently.

***Steps to reproduce the behavior:***

1. Create a Magma server
2. Login with two players
3. Use an RPG, M202, grenade, directly on the player

## Versions

- Modern Warfare Cubed: MWC-0.1-Dev-10
- Forge: 1.12.2 - 14.23.5.2860
- Java: JDK 8
- Host: apexhosting

## Specification:
- RAM Allocated: 4.5GB

**Comment by SticksDeveloper** [comment] 2023-05-12 07:38
I believe you need to downgrade Magma a bit or try dev-9 to see If It's the same issue

**Comment by BoomerSchmirtz** [comment] 2023-05-12 07:42
Didn't occur on DEV-9 and Magma version wasn't changed since

**Comment by markgyoni** [comment] 2023-05-12 09:28
Hey, I can also confirm this with my server. Also, did anyone test this on a standard Forge server? If not, then I'm willing to do it later today.

**Comment by Paneedah** [comment] 2023-05-12 09:52
I'm pretty sure it's a side effect of something that we did. @SticksDeveloper please look into this ASAP and compare what was changed between now and Dev-9.

**Comment by Paneedah** [comment] 2023-05-12 13:09
Desoro if you read the issue: there is no error nor message sent in the logs when the issue happens.

**Comment by BoomerSchmirtz** [comment] 2023-05-12 13:10
Nothing is being prompted to the console. Is there a specific file that contains more data?

@markgyoni did you guys encounter any errors in the logs?

**Comment by BoomerSchmirtz** [comment] 2023-05-12 14:20
Here's what I could find from the logs

**This is from the local debug log (in %appdata%)**

`[17:15:23] [Client thread/DEBUG] [mwc]: Changed state of rpg7[6eddc231-5b44-4f9d-a41d-02f8ab8251e4] to LOAD_REQUESTED
[17:15:23] [Client thread/DEBUG] [mwc]: Syncing rpg7[6eddc231-5b44-4f9d-a41d-02f8ab8251e4] in state LOAD_REQUESTED with update id 121 to server
[17:15:33] [Thread-5/DEBUG] [mwc]: Changed state of rpg7[6eddc231-5b44-4f9d-a41d-02f8ab8251e4] to READY
[17:15:33] [Thread-5/ERROR] [mwc]: Permit is null, something went wrong
[17:15:33] [Client thread/DEBUG] [mwc]: Syncing rpg7[6eddc231-5b44-4f9d-a41d-02f8ab8251e4] in state READY with update id 122 to server
[17:15:43] [Client thread/DEBUG] [mwc]: Syncing rpg7[6eddc231-5b44-4f9d-a41d-02f8ab8251e4] in state READY with update id 122 to server
[17:15:52] [Netty Client IO #7/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException: null`

**That's from local latest.log (%appdata%)**
`[14:15:22] [Server thread/DEBUG] [mwc]: Processing permit com.paneedah.weaponlib.state.Permit@3a46d8d1 for instance rpg7[6eddc231-5b44-4f9d-a41d-02f8ab8251e4]
[14:15:22] [Server thread/DEBUG] [mwc]: Syncing rpg7[6eddc231-5b44-4f9d-a41d-02f8ab8251e4] in state PAUSED on server
[14:15:22] [Server thread/DEBUG] [mwc]: Stored instance rpg7[6eddc231-5b44-4f9d-a41d-02f8ab8251e4] of com.paneedah.weaponlib.Weapon@4791d5c8 in stack 1xitem.rpg7@0
[14:15:22] [Server thread/DEBUG] [mwc]: Processing permit com.paneedah.weaponlib.state.Permit@92377778 for instance rpg7[6eddc231-5b44-4f9d-a41d-02f8ab8251e4]
[14:15:22] [Server thread/DEBUG] [mwc]: Syncing rpg7[6eddc231-5b44-4f9d-a41d-02f8ab8251e4] in state READY on server
[14:15:22] [Server thread/DEBUG] [mwc]: Stored instance rpg7[6eddc231-5b44-4f9d-a41d-02f8ab8251e4] of com.paneedah.weaponlib.Weapon@4791d5c8 in stack 1xitem.rpg7@0`

**And that's from the server itself**
`[17:15:52] [Netty Client IO #7/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException: null
[17:15:52] [Client thread/INFO] [voicechat]: Clearing audio channels
[17:15:52] [Client thread/INFO] [voicechat]: Stopping microphone thread
[17:15:52] [Client thread/INFO] [voicechat]: Disconnecting voicechat
[17:15:53] [Client thread/INFO] [FML]: Applying holder lookups
[17:15:53] [Client thread/INFO] [FML]: Holder lookups applied
`

**Comment by Desoroxxx** [comment] 2023-05-12 14:22
Oh, that issue is because of Magma, we can't really do anything special about it.

Might be fixed with #46 cross your fingers.

**Closed by Desoroxxx** 2023-05-12 14:22 UTC
Labels: Bug

**Comment by Desoroxxx** [comment] 2023-05-12 14:39
> Should we switch to CatServer? Should we wait until next DEV version?

I can't give you any information on that, you should wait t'ill the entire compatibility package is removed more info in #46 

> Have you guys done tests with Magma with the compatibility removal? Do you know this is what causes the issues with explosions?

Well, the problem is Magma trying to check against a vanilla feature that MWC compatibility package wouldn't have or returns null, thus #46 would fix it

**Comment by BoomerSchmirtz** [comment] 2023-05-12 14:41
Got it. Thanks for explaining! 
This is really good news for me and @markgyoni :)

If you need help with testing it against a Magma server when it's possible - hit me up
